### PR TITLE
fix(iOS): handle NSNull in style prop to prevent crash

### LINKED ISSUE #1267: Crash with raster layer: uncaught exception 'NSInvalidArgumentException'
### Describe and reproduce the Bug

Our app is crashing when we try swich a raster source/layer. 

Error:

```
[CoreFoundation] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull allKeys]: unrecognized selector sent to instance 0x1e3b3ba80'
*** First throw call stack:
(
0   CoreFoundation                      0x00000001804b910c __exceptionPreprocess + 172
1   libobjc.A.dylib                     0x0000000180092da8 objc_exception_throw + 72
2   CoreFoundation                      0x00000001804cebf4 +[NSObject(NSObject) instanceMethodSignatureForSelector:] + 0
3   CoreFoundation                      0x00000001804bd40c ___forwarding___ + 1268
4   CoreFoundation                      0x00000001804bfb2c _CF_forwarding_prep_0 + 92
5   UTdev.debug.dylib                   0x000000010b2d1248 -[MLRNStyle _hasReactStyle:] + 88
6   UTdev.debug.dylib                   0x000000010b2c7f6c -[MLRNStyle rasterLayer:withReactStyle:isValid:] + 116
7   UTdev.debug.dylib                   0x000000010b282b40 -[MLRNLayer addStyles] + 972
8   UTdev.debug.dylib                   0x000000010b2820a4 -[ML<…>
```
 
This happens when one `<RasterSource><Layer type="raster" /></RasterSource>` is removed and another is added (switching a basemap). This worked in earlier v11 alpha versions. 

### @maplibre/maplibre-react-native Version

11.0.0-alpha.41

### Which platforms does this occur on?

iOS Simulator

### Which frameworks does this occur on?

Expo

### Which architectures does this occur on?

New Architecture

### Environment

```text
expo-env-info 2.0.8 environment info:
    System:
      OS: macOS 26.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.21.1 - ~/.nvm/versions/node/v22.21.1/bin/node
      Yarn: 1.22.22 - ~/.yarn/bin/yarn
      npm: 10.9.4 - ~/.nvm/versions/node/v22.21.1/bin/npm
      Watchman: 2025.04.14.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 25.2, iOS 26.2, macOS 26.2, tvOS 26.2, visionOS 26.2, watchOS 26.2
      Android SDK:
        API Levels: 28, 34, 35, 36
        Build Tools: 34.0.0, 35.0.0, 35.0.1, 36.0.0
        System Images: android-36 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2025.2 AI-252.28238.7.2523.14688667
      Xcode: 26.2/17C52 - /usr/bin/xcodebuild
    npmPackages:
      expo: 54.0.31 => 54.0.31 
      expo-router: 6.0.21 => 6.0.21 
      expo-updates: 29.0.16 => 29.0.16 
      metro: ^0.83.1 => 0.83.3 
      react: 19.1.0 => 19.1.0 
      react-dom: 19.1.0 => 19.1.0 
      react-native: 0.81.5 => 0.81.5 
      react-native-web: ^0.21.0 => 0.21.2 
    npmGlobalPackages:
      eas-cli: 16.28.0
    Expo Workflow: bare
```

### PR DESCRIPTION
**Pull request by tyrauber**
## Summary
- Fixes iOS crash when switching between layers where one has a style prop and one doesn't
- New Architecture passes NSNull instead of nil for missing optional props
- Added NSNull check in _hasReactStyle: method to handle this case

Fixes #1267

## Test plan
- [x] Verified crash reproduction with scenario from issue
- [x] Confirmed fix resolves the crash
- [x] Ran codegen to regenerate native code from template

### CODE REVIEW

**Review by KiwiKilian — CHANGES_REQUESTED** [review]
I think it would be more in line to check during the prop setting, like we do already for other components/props, for example:


```obj-c
(!newViewProps.light.isNull() && newViewProps.light.isObject())
                                   ? convertFollyDynamicToId(newViewProps.light)
                                   : nil;
```

Maybe we could create a global util/macro for this?

File: ios/components/layers/MLRNLayerComponentView.mm [hunk 1]
```diff
@@ -10,7 +10,7 @@
 #import <MapLibre/MapLibre.h>
 #import <React/RCTBridge+Private.h>
 #import <React/RCTConversions.h>
-#import "MLRNFollyConvert.h"
+#import "../../utils/MLRNPropConvert.h"
```
Comment (KiwiKilian) [inline ios/components/layers/MLRNLayerComponentView.mm]: Any reason to have a relative Import here?

Comment (tyrauber) [reply ios/components/layers/MLRNLayerComponentView.mm]: I had a build error the other way, but maybe I just needed didn't properly do a prebuild --clean before testing. Trying again.

**Review by KiwiKilian — APPROVED** [review]
