### PR TITLE
fix: usage of PMTiles on iOS 17 through VectorSource with NSString

### LINKED ISSUE #618: PMTiles URL schema throws error in iOS
### Describe and reproduce the Bug

iOS uses `NSUrl` to represent the maplibre tile source. This type doesn't recognize `pmtiles://https://<rest-of-url>` as a valid url and throws an error:

```
MapLibre error Requesting: https//nrs.objectstore.gov.bc.ca/lwzrin/psu/pmtiles/fireCentres.pmtiles failed with error: Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSLocalizedDescription=unsupported URL, NSErrorFailingURLStringKey=https//nrs.objectstore.gov.bc.ca/lwzrin/psu/pmtiles/fireCentres.pmtiles, NSErrorFailingURLKey=https//nrs.objectstore.gov.bc.ca/lwzrin/psu/pmtiles/fireCentres.pmtiles, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <6816E63E-8AC6-413A-B987-B1B2F8D969DD>.<2>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <6816E63E-8AC6-413A-B987-B1B2F8D969DD>.<2>, NSUnderlyingError=0x600000d025b0 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 "(null)"}} {"filePath": "-[MLNNetworkConfiguration errorLog:]", "level": "error", "line": 129, "message": "Requesting: https//nrs.objectstore.gov.bc.ca/lwzrin/psu/pmtiles/fireCentres.pmtiles failed with error: Error Domain=NSURLErrorDomain Code=-1002 \"unsupported URL\" UserInfo={NSLocalizedDescription=unsupported URL, NSErrorFailingURLStringKey=https//nrs.objectstore.gov.bc.ca/lwzrin/psu/pmtiles/fireCentres.pmtiles, NSErrorFailingURLKey=https//nrs.objectstore.gov.bc.ca/lwzrin/psu/pmtiles/fireCentres.pmtiles, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    \"LocalDataTask <6816E63E-8AC6-413A-B987-B1B2F8D969DD>.<2>\"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <6816E63E-8AC6-413A-B987-B1B2F8D969DD>.<2>, NSUnderlyingError=0x600000d025b0 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 \"(null)\"}}"}
```

The likely fix is to use a type other than `NSUrl` to represent the URL for the tile source, perhaps a string or more constrained type.

Repro repo is here: https://github.com/conbrad/pmtiles-ios-bug

### @maplibre/maplibre-react-native Version

10.0.0

### Which platforms does this occur on?

iOS Simulator, iOS Device

### Which frameworks does this occur on?

Expo, React Native

### Which architectures does this occur on?

_No response_

### Environment

```text
expo-env-info 1.2.2 environment info:
    System:
      OS: macOS 15.2
      Shell: 3.7.1 - /opt/homebrew/bin/fish
    Binaries:
      Node: 22.12.0 - /usr/local/bin/node
      Yarn: 1.22.22 - /usr/local/bin/yarn
      npm: 10.9.0 - /usr/local/bin/npm
      Watchman: 2024.12.02.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.2 - /Users/cbrady/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.2, iOS 18.2, macOS 15.2, tvOS 18.2, visionOS 2.2, watchOS 11.2
    IDEs:
      Android Studio: 2024.2 AI-242.23339.11.2421.12700392
      Xcode: 16.2/16C5032a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.25 => 52.0.25
      expo-router: ~4.0.16 => 4.0.16
      react: 18.3.1 => 18.3.1
      react-dom: 18.3.1 => 18.3.1
      react-native: 0.76.6 => 0.76.6
      react-native-web: ~0.19.13 => 0.19.13
    Expo Workflow: bare
```

### PR DESCRIPTION
**Pull request by KiwiKilian**
Fixes #618 

To test, use this Bug Report example https://github.com/maplibre/maplibre-react-native/issues/618#issuecomment-2593818551

Now it also works on iOS 17.

### CODE REVIEW

**Comment by KiwiKilian** [comment]
@conbrad could you please also have a look at this?

File: ios/MLRN/MLRNVectorSource.m [hunk 1]
```diff
@@ -5,7 +5,11 @@ @implementation MLRNVectorSource
 - (nullable MLNSource*)makeSource
 {
     if (self.url != nil) {
+      if([self.url hasPrefix:@"pmtiles://"]) {
+        return [[MLNVectorTileSource alloc] initWithIdentifier:self.id tileURLTemplates:@[self.url] options:nil];
```
Comment (tyrauber) [inline ios/MLRN/MLRNVectorSource.m]: No options? Is that because self.url contains all the params?

**Comment by conbrad** [comment]
> @conbrad could you please also have a look at this?

Looks reasonable, however is it possible to simplify, remove the conditional block and just always use `tileUrlTemplates`, at least until a proper fix is in place?

Regarding @tyrauber 's [comment](https://github.com/maplibre/maplibre-react-native/pull/625#discussion_r1922735492) , I believe PMTiles relies solely on HTTP headers, so URL params shouldn't be a factor, unless of course you're using params through a proxy or something...

**Comment by KiwiKilian** [comment]
@conbrad see my comment here https://github.com/maplibre/maplibre-native/issues/3151#issuecomment-2603220223 regarding only using `tileUrlTemplates`.

File: ios/MLRN/MLRNVectorSource.m (hunk 1 above)
Comment (KiwiKilian) [reply ios/MLRN/MLRNVectorSource.m]: Valid request, as it allows to pass the attribution, tested and works. Min/max zoom should be delivered through PMTiles, but it might also be possible to overwrite this way.

**Review by conbrad — APPROVED** [review]
LGTM!

**Comment by KiwiKilian** [comment]
I've posted a workaround to the issue. Therefore lets wait for the release of the fix https://github.com/maplibre/maplibre-native/pull/3163 upstream, then I will adopt this PR.

**Comment by KiwiKilian** [comment]
This is now ready for review, to be merged after #650.

**Review by tyrauber — APPROVED** [review]
I think this builds on the other PR updated the native SDK, but the protomap code looks cleaner.  Nice!
